# Generated by Django 3.1.5 on 2021-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMakanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('gambar_makanan', models.CharField(max_length=100)),
                ('harga_makanan', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
