# Generated by Django 3.1.5 on 2021-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20210114_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenumodel',
            name='price_food',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
