# Generated by Django 3.1.5 on 2021-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_auto_20210114_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenumodel',
            name='image_food',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
