# Generated by Django 3.1.5 on 2021-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_auto_20210114_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_pic', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('food_cat', models.CharField(max_length=100)),
                ('food_price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodMenuModel',
        ),
    ]
