# Generated by Django 3.1.5 on 2021-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_auto_20210115_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
