# Generated by Django 3.1.1 on 2021-01-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0008_menumodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
